### PR TITLE
ENH: NumPy 2 compat

### PR DESCRIPTION
**Pull request by larsoner**
1. Build the wheel on Python 3.9 now (that's the oldest Python that NumPy 2.0 was released against)
2. Build against NumPy 2.0, which has code that is both 1.x and 2.0+ compatible
3. Bump cibuildwheel version
4. Run on PRs (like this one) to make sure things work
5. Fix testing of `sdist` (previously the install step ignored `dist/` and just installed from PyPI!)
6. Append `.post1` to the PTB version since we're using the same PTB (3.0.19.0) but this is a post-release fix at our end
7. Cleanups/updates the the action (e.g., action versions and concurrency auto-cancelling for builds)
8. Adding `dependabot.yml` (keep actions up to date) and `release.yaml` (in case you want to use GitHub's automated release notes stuff, it'll ignore the dependabot PRs)
9. Fix implicit delocation error where the macOS deployment target was errantly set too low (one of the PTB dylibs was compiled with a 13 min target)

Draft until https://github.com/aforren1/Psychtoolbox-3/pull/1 lands and I can revert the branch name change

### CODE REVIEW

**Comment by larsoner** [comment]
All green [over in my fork](https://github.com/larsoner/ptb-wheels/actions/runs/10096072041) and updated the version number to have a `.post1` at the end, so in theory if you approve the run @aforren1 it should be green here, too. Then we can merge https://github.com/aforren1/Psychtoolbox-3/pull/1 if you're happy, I can update the URL and commit hash in the submodule back to yours, then a new release would in theory build and push to PyPI NumPy 2.0-compatible wheels 🤞

**Comment by aforren1** [comment]
Thanks for fixing this up. All generally looks fine, and a few thoughts below:

 - Don't worry about targeting my fork of PTB, that change has been merged [upstream](https://github.com/kleinerm/Psychtoolbox-3) and I'll probably just point the submodule either there or the main repository if there's an impending release.
 - Does anyone (i.e. PsychoPy) _need_ 3.8 support? Last I checked, they still release 3.8 versions, though I'm not sure if there's a specific reason at this point...
 - It looks like this would end up dropping NumPy 1.x support, does anyone still need the older NumPy? It looks like supporting both old and new isn't too bad, just adding a `dependencies` section (https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice)? And in that case, targeting 1.25 and adding  `NPY_TARGET_VERSION`, see [here](https://numpy.org/doc/stable/release/1.25.0-notes.html#compiling-against-the-numpy-c-api-is-now-backwards-compatible-by-default)?
 - Maybe I'm misreading, but as-is this drops testing the built wheels against later versions of Python? It might be redundant, but IIRC this has caught a few things in the past.
 - Have you tried any tests with physical devices locally, e.g. the demos in the PsychPython/demos/ folder?

**Comment by larsoner** [comment]
> Does anyone (i.e. PsychoPy) need 3.8 support? Last I checked, they still release 3.8 versions, though I'm not sure if there's a specific reason at this point...

3.8 is [very close to EOL at 2024-10](https://devguide.python.org/versions/#python-release-cycle) and most packages have dropped support (see e.g. [SPEC0](https://scientific-python.org/specs/spec-0000/)). I see this as mostly a maintenance fix for NumPy 2.0 (current wheels are totally broken) and that's only 3.9+ so I think it's to support 3.9+ only. But actually since the wheels are ABI-limited anyway they seem to be generated with 3.7+ name so 3.8 might even still work.

> It looks like this would end up dropping NumPy 1.x support

It shouldn't, wheels [compiled with 2.x create 1.x compatible code](https://numpy.org/doc/stable/dev/depending_on_numpy.html#numpy-2-0-specific-advice), too. But since I'm going to add some tests (see below) I'll make sure one of them uses `numpy<2` just so we can all sleep well at night.

> but as-is this drops testing the built wheels against later versions of Python? It might be redundant, but IIRC this has caught a few things in the past.

Yes it does -- currently you build and test on all versions of Python but that's a lot of extra work. I'll push some commits to build the ABI limited wheel but test it on other platforms (at least to the extent it's currently tested, which appears just to try to get a time output!).

> Have you tried any tests with physical devices locally, e.g. the demos in the PsychPython/demos/ folder?

No, I'll do that hopefully today!

**Comment by larsoner** [comment]
> Have you tried any tests with physical devices locally, e.g. the demos in the PsychPython/demos/ folder?

Locally `PsychPython/demos/ppatest_pythonic.py` worked for me -- played a couple of very loud beeps once I modified line 43 to have `audio.Stream(..., device_id=7)` and use the device that I typically play sounds with.

Pushed some commits -- now it tests on 3.9 and 3.12 on all three platforms, and has one test on 3.9 and `numpy<2` on Ubuntu. Can add more tests if needed but this seemed good enough. I improved the test to make sure an audio device is actually available in the device list by using [`sound-ci-helpers`](https://github.com/LABSN/sound-ci-helpers/) (which I maintain). But it seems like it does not actually work on Linux despite `python -m sounddevice` listing audio devices, and some `rtmixer` (which also compiles PortAudio) wheel testing seeming to work:

https://github.com/larsoner/ptb-wheels/actions/runs/10150685048/job/28068595123

I initially thought it was just a problem in the docker instance in `cibuildwheel` so I skip the test there with `PTB_SOUND_TEST=0`. But then even downloading and installing the wheel on Ubuntu 22.04 (even after installing `libportaudio2`, which shouldn't be necessary but I did to try to help) didn't seem to work. I'll have to download the wheel locally and see if it works. 😞 

If it works locally (and the previously released wheel does, too) then I might have to abandon trying to test the sound output on Linux CIs for now.

**Comment by larsoner** [comment]
Well, the good news is that locally the wheel downloaded from the actions link above works fine on my Ubuntu system. The bad news is that I can't figure out how to make it work on CIs. So for now I'm just going to disable it on Ubuntu.

**Comment by larsoner** [comment]
Okay @aforren1 the [CI run](https://github.com/larsoner/ptb-wheels/actions/runs/10182572291) for [54b65ef](https://github.com/aforren1/ptb-wheels/pull/10/commits/54b65eff1d262b9c1ab1c8b56423bc7f055ba5de) is green! If you click the "approve" button on CIs then it should hopefully comes back green here, too.

We could then wait for the upstream PR https://github.com/Psychtoolbox-3/Psychtoolbox-3/pull/843 to be merged (this PR does use https://github.com/Psychtoolbox-3/Psychtoolbox-3/pull/843/commits/22939b1dc186825d6fb24366aa5175611fbc0f6f from that PR) but given the lack of activity I'd suggest to merge this as-is and then a quick release so that https://github.com/psychopy/psychopy/pull/6744 can move forward. Whenever you decide to merge, I'd suggest a squash+merge to get rid of all the silly commit messages I used :smile: (Or I can squash locally and force-push if you want.)

**Comment by aforren1** [comment]
Sorry for the delay, I'll probably have some time to think about this next week?

For best results on the upstream PR, you'll probably want to squash your commits into 1. numpy2 compat, 2. desc fix, and add some more details (see e.g. https://github.com/Psychtoolbox-3/Psychtoolbox-3/pull/766#issuecomment-1126796003 for Mario's requests on a previous PR). A description fix is already in [Mario's fork](https://github.com/kleinerm/Psychtoolbox-3/pull/274) (which is the most upstream), but yours is better.

**Comment by larsoner** [comment]
Awesome, thanks for the hints! I opened https://github.com/kleinerm/Psychtoolbox-3/pull/276

**Comment by larsoner** [comment]
... updated to the commit in my new PR and still all green 🚀 https://github.com/larsoner/ptb-wheels/actions/runs/10229193807

**Comment by larsoner** [comment]
Okay upstream PR merged, pushed an update to use `upstream/master` commit https://github.com/kleinerm/Psychtoolbox-3/commit/6dc77de0036358dc597778820c1e3ee0b1939e10, and [the action in my fork is still green](https://github.com/larsoner/ptb-wheels/actions/runs/10240211890) !

**Comment by larsoner** [comment]
All green here, too, looks like!

**Comment by aforren1** [comment]
Thanks for pushing on this! I had a chance to test & all looks fine locally. Were you able to test on a Mac?

**Comment by larsoner** [comment]
Not 100% sure but I don't think I did

**Comment by larsoner** [comment]
Any plans to cut a release to get the wheels up on PyPI?

**Comment by aforren1** [comment]
The first Mac user I ran into is still on 12.x (which also looks like it's nearly EOL, but 🤷), so I was thinking about whether or not to drop bundling libusb (which I started bundling in https://github.com/aforren1/ptb-wheels/pull/8/commits/244bf074779e080a848910896123337a3047bb08) for now to ease that requirement. In principle, the user can just install from brew/elsewhere?

**Comment by larsoner** [comment]
It's pretty standard to bundle libs. I think if you don't, a lot of people will be confused why things don't work. And making people do stuff with `brew` is kind of a pain. :disappointed: And these people on pre-13 versions would presumably be in trouble with the official MATLAB psychtoolbox binaries, so in that sense we're just following suit :shrug: 

I think the right thing to do would be to fix the upstream bug of having compiled the library with a 13 target. It should probably be 11 if possible. I could look into this potentially at some point.

In the meantime, in this PR I added this:

https://github.com/aforren1/ptb-wheels/pull/10/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R19

```
  CIBW_ENVIRONMENT_MACOS: CC=clang PTB_LIMITED_WHEEL=1 MACOSX_DEPLOYMENT_TARGET=13.0
```

IIRC the reason was exactly because of that 13-compiled lib -- `cibuildwheel` (rightly) bundled libraries, then (rightly) complained that the default build target of 11 and resulting wheel naming (!) was not actually achieved/correct.

So my vote would be to 1) stick with the 13 target for now, people who need 11 or 12 could maybe install an old version (?) for now, and 2) the upstream build target should be fixed, and then 3) new wheels could be released that are 11 or 12 compatible.

**Comment by aforren1** [comment]
Building a libusb with the older target seems to work (https://github.com/aforren1/ptb-wheels/pull/13)? Upstream PTB doesn't bundle libusb for Macs, so this dylib was coming from the runner.

I'll cut a release once I can double-check with the local Mac user. If you want to try, the minimal libusb exercise is:

```python
from psychtoolbox import PsychHID
assert(PsychHID('OpenUSBDevice', -1, -1) == 1)
```

**Comment by larsoner** [comment]
> Building a libusb with the older target seems to work (#13)? 

Awesome!

> If you want to try, the minimal libusb exercise is:

We could try adding this to the cibuildwheel test, would be neat if it worked on all platforms. I can make a quick PR for this if you want

**Comment by aforren1** [comment]
Tried adding the libusb test in #14. but... https://github.com/aforren1/ptb-wheels/actions/runs/10739118053/job/29784142768#step:8:1294

**Pull request merged**
